POST {{host}}/user
Accept: application/json
Content-Type: application/json

{
  "name": "Nguyễn Quang Lý",
  "gender": "FEMALE"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
j = response.body.data.user
client.test("Correct response", function() {
  client.assert(j.name == "Nguyễn Quang Lý", "Wrong name")
});
client.global.set("campaign_id", j.id)
%}

###

GET {{host}}/user/{{campaign_id}}
Accept: application/json
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
j = response.body.data.user
client.test("Correct response", function() {
  client.assert(j.id == client.global.get("campaign_id"), "Wrong id")
});
%}

###
PATCH {{host}}/user/{{campaign_id}}
Accept: application/json
Content-Type: application/json

{
  "gender": "MALE"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
j = response.body.data.user
client.test("Correct response", function() {
  client.assert(j.gender === "MALE", "Wrong id")
});
%}

###
GET {{host}}/users?order_by=id.desc
Accept: application/json
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}